### ISSUE TITLE
SMTPRecipientsRefused(senderrs)

### ISSUE THREAD

**Issue by PedroKirwan** [chrisalbon/notes#63]
I'm aware this isn't a problem with the script but was wondering if anyone else has encountered this problem and knows how to get around it

Traceback (most recent call last):
  File ".\Users\redacted\Documents\security-education\checkscvo.py", line 56, in <module>
    server.sendmail(fromaddr, toaddrs, msg)
  File "C:\Program Files\Python36\lib\smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'redacted@redacted.net'}

**Comment by PedroKirwan** [comment]
closing because it was me being stupid and leaving some stuff commented! If you have this problem check you've uncommented stuff.
